package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresses generated by hbm2java
 */
@Entity
@Table(name = "adresses", catalog = "vereinsdb")
public class Adress implements java.io.Serializable {

	private Integer adressId;
	private String streetName;
	private int number;
	private int plz;
	private String city;
	private Set<Lease> leaseses = new HashSet<Lease>(0);
	private Set<Member> memberses = new HashSet<Member>(0);

	public Adress() {
	}

	public Adress(String streetName, int number, int plz, String city) {
		this.streetName = streetName;
		this.number = number;
		this.plz = plz;
		this.city = city;
	}

	public Adress(String streetName, int number, int plz, String city, Set<Lease> leaseses, Set<Member> memberses) {
		this.streetName = streetName;
		this.number = number;
		this.plz = plz;
		this.city = city;
		this.leaseses = leaseses;
		this.memberses = memberses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "adress_ID", unique = true, nullable = false)
	public Integer getAdressId() {
		return this.adressId;
	}

	public void setAdressId(Integer adressId) {
		this.adressId = adressId;
	}

	@Column(name = "streetName", nullable = false, length = 45)
	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "plz", nullable = false)
	public int getPlz() {
		return this.plz;
	}

	public void setPlz(int plz) {
		this.plz = plz;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresses")
	public Set<Lease> getLeaseses() {
		return this.leaseses;
	}

	public void setLeaseses(Set<Lease> leaseses) {
		this.leaseses = leaseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adresses")
	public Set<Member> getMemberses() {
		return this.memberses;
	}

	public void setMemberses(Set<Member> memberses) {
		this.memberses = memberses;
	}

}
