package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Devices generated by hbm2java
 */
@Entity
@Table(name = "devices", catalog = "vereinsdb")
public class Device implements java.io.Serializable {

	private Integer deviceId;
	private DeviceStorage deviceStorages;
	private Kategory kategories;

	public Device() {
	}

	public Device(DeviceStorage deviceStorages, Kategory kategories) {
		this.deviceStorages = deviceStorages;
		this.kategories = kategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "device_ID", unique = true, nullable = false)
	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_storage_ID", nullable = false)
	public DeviceStorage getDeviceStorages() {
		return this.deviceStorages;
	}

	public void setDeviceStorages(DeviceStorage deviceStorages) {
		this.deviceStorages = deviceStorages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kategory_ID", nullable = false)
	public Kategory getKategories() {
		return this.kategories;
	}

	public void setKategories(Kategory kategories) {
		this.kategories = kategories;
	}

}
