package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeviceStorages generated by hbm2java
 */
@Entity
@Table(name = "device_storages", catalog = "vereinsdb")
public class DeviceStorage implements java.io.Serializable {

	private Integer deviceStorageId;
	private int adressId;
	private Set<Device> deviceses = new HashSet<Device>(0);

	public DeviceStorage() {
	}

	public DeviceStorage(int adressId) {
		this.adressId = adressId;
	}

	public DeviceStorage(int adressId, Set<Device> deviceses) {
		this.adressId = adressId;
		this.deviceses = deviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "device_storage_ID", unique = true, nullable = false)
	public Integer getDeviceStorageId() {
		return this.deviceStorageId;
	}

	public void setDeviceStorageId(Integer deviceStorageId) {
		this.deviceStorageId = deviceStorageId;
	}

	@Column(name = "adress_ID", nullable = false)
	public int getAdressId() {
		return this.adressId;
	}

	public void setAdressId(int adressId) {
		this.adressId = adressId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceStorages")
	public Set<Device> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Device> deviceses) {
		this.deviceses = deviceses;
	}

}
