package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Donator generated by hbm2java
 */
@Entity
@Table(name = "donator", catalog = "vereinsdb")
public class Donator implements java.io.Serializable {

	private Integer donatorId;
	private Dontation dontations;
	private User users;
	private double donations;

	public Donator() {
	}

	public Donator(Dontation dontations, User users, double donations) {
		this.dontations = dontations;
		this.users = users;
		this.donations = donations;
	}

	@GenericGenerator(name = "com.verein.entity.DonatorIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "com.verein.entity.DonatorIdGenerator")

	@Column(name = "donator_ID", unique = true, nullable = false)
	public Integer getDonatorId() {
		return this.donatorId;
	}

	public void setDonatorId(Integer donatorId) {
		this.donatorId = donatorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "donations_ID", nullable = false)
	public Dontation getDontations() {
		return this.dontations;
	}

	public void setDontations(Dontation dontations) {
		this.dontations = dontations;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	@Column(name = "donations", nullable = false, precision = 22, scale = 0)
	public double getDonations() {
		return this.donations;
	}

	public void setDonations(double donations) {
		this.donations = donations;
	}

}
