package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dontations generated by hbm2java
 */
@Entity
@Table(name = "dontations", catalog = "vereinsdb")
public class Dontation implements java.io.Serializable {

	private Integer dontationsId;
	private double donation;
	private Date date;
	private Set<Donator> donators = new HashSet<Donator>(0);

	public Dontation() {
	}

	public Dontation(double donation, Date date) {
		this.donation = donation;
		this.date = date;
	}

	public Dontation(double donation, Date date, Set<Donator> donators) {
		this.donation = donation;
		this.date = date;
		this.donators = donators;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dontations_ID", unique = true, nullable = false)
	public Integer getDontationsId() {
		return this.dontationsId;
	}

	public void setDontationsId(Integer dontationsId) {
		this.dontationsId = dontationsId;
	}

	@Column(name = "donation", nullable = false, precision = 22, scale = 0)
	public double getDonation() {
		return this.donation;
	}

	public void setDonation(double donation) {
		this.donation = donation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dontations")
	public Set<Donator> getDonators() {
		return this.donators;
	}

	public void setDonators(Set<Donator> donators) {
		this.donators = donators;
	}

}
