package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kategories generated by hbm2java
 */
@Entity
@Table(name = "kategories", catalog = "vereinsdb")
public class Kategory implements java.io.Serializable {

	private Integer kategoryId;
	private String titel;
	private String description;
	private Set<Device> deviceses = new HashSet<Device>(0);

	public Kategory() {
	}

	public Kategory(String titel, String description) {
		this.titel = titel;
		this.description = description;
	}

	public Kategory(String titel, String description, Set<Device> deviceses) {
		this.titel = titel;
		this.description = description;
		this.deviceses = deviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "kategory_ID", unique = true, nullable = false)
	public Integer getKategoryId() {
		return this.kategoryId;
	}

	public void setKategoryId(Integer kategoryId) {
		this.kategoryId = kategoryId;
	}

	@Column(name = "titel", nullable = false, length = 45)
	public String getTitel() {
		return this.titel;
	}

	public void setTitel(String titel) {
		this.titel = titel;
	}

	@Column(name = "description", nullable = false, length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kategories")
	public Set<Device> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Device> deviceses) {
		this.deviceses = deviceses;
	}

}
