package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Lessees generated by hbm2java
 */
@Entity
@Table(name = "lessees", catalog = "vereinsdb")
public class Lessee implements java.io.Serializable {

	private Integer lesseeId;
	private Lease leases;
	private User users;

	public Lessee() {
	}

	public Lessee(Lease leases, User users) {
		this.leases = leases;
		this.users = users;
	}

	@GenericGenerator(name = "com.verein.entity.LesseesIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "com.verein.entity.LesseesIdGenerator")

	@Column(name = "lessee_ID", unique = true, nullable = false)
	public Integer getLesseeId() {
		return this.lesseeId;
	}

	public void setLesseeId(Integer lesseeId) {
		this.lesseeId = lesseeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "leases_ID", nullable = false)
	public Lease getLeases() {
		return this.leases;
	}

	public void setLeases(Lease leases) {
		this.leases = leases;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

}
