package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Members generated by hbm2java
 */
@Entity
@Table(name = "members", catalog = "vereinsdb")
public class Member implements java.io.Serializable {

	private Integer memberId;
	private Adress adresses;
	private User users;
	private Date memberSince;
	private double openBills;
	private double openHours;

	public Member() {
	}

	public Member(Adress adresses, User users, Date memberSince, double openBills, double openHours) {
		this.adresses = adresses;
		this.users = users;
		this.memberSince = memberSince;
		this.openBills = openBills;
		this.openHours = openHours;
	}

	@GenericGenerator(name = "com.verein.entity.MembersIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "com.verein.entity.MembersIdGenerator")

	@Column(name = "member_ID", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "memberAdress_ID", nullable = false)
	public Adress getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Adress adresses) {
		this.adresses = adresses;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "member_since", nullable = false, length = 10)
	public Date getMemberSince() {
		return this.memberSince;
	}

	public void setMemberSince(Date memberSince) {
		this.memberSince = memberSince;
	}

	@Column(name = "openBills", nullable = false, precision = 22, scale = 0)
	public double getOpenBills() {
		return this.openBills;
	}

	public void setOpenBills(double openBills) {
		this.openBills = openBills;
	}

	@Column(name = "openHours", nullable = false, precision = 22, scale = 0)
	public double getOpenHours() {
		return this.openHours;
	}

	public void setOpenHours(double openHours) {
		this.openHours = openHours;
	}

}
