package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MonthlyIncomings generated by hbm2java
 */
@Entity
@Table(name = "monthly_incomings", catalog = "vereinsdb")
public class MonthlyIncoming implements java.io.Serializable {

	private Integer monthlyIncomingsId;
	private double income;
	private String month;
	private int year;

	public MonthlyIncoming() {
	}

	public MonthlyIncoming(double income, String month, int year) {
		this.income = income;
		this.month = month;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "monthly_incomings_ID", unique = true, nullable = false)
	public Integer getMonthlyIncomingsId() {
		return this.monthlyIncomingsId;
	}

	public void setMonthlyIncomingsId(Integer monthlyIncomingsId) {
		this.monthlyIncomingsId = monthlyIncomingsId;
	}

	@Column(name = "income", nullable = false, precision = 22, scale = 0)
	public double getIncome() {
		return this.income;
	}

	public void setIncome(double income) {
		this.income = income;
	}

	@Column(name = "month", nullable = false, length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

}
