package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MonthlyExpenditures generated by hbm2java
 */
@Entity
@Table(name = "monthly_expenditures", catalog = "vereinsdb")
public class MonthlyExpenditure implements java.io.Serializable {

	private Integer monthlyExpendituresId;
	private double expenditure;
	private String month;
	private int year;

	public MonthlyExpenditure() {
	}

	public MonthlyExpenditure(double expenditure, String month, int year) {
		this.expenditure = expenditure;
		this.month = month;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "monthly_expenditures_ID", unique = true, nullable = false)
	public Integer getMonthlyExpendituresId() {
		return this.monthlyExpendituresId;
	}

	public void setMonthlyExpendituresId(Integer monthlyExpendituresId) {
		this.monthlyExpendituresId = monthlyExpendituresId;
	}

	@Column(name = "expenditure", nullable = false, precision = 22, scale = 0)
	public double getExpenditure() {
		return this.expenditure;
	}

	public void setExpenditure(double expenditure) {
		this.expenditure = expenditure;
	}

	@Column(name = "month", nullable = false, length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

}
