package com.verein.entity;
// Generated 02.05.2022 19:10:50 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "vereinsdb")
public class User implements java.io.Serializable {

	private Integer userId;
	private String firstName;
	private String lastName;
	private Date birthdate;
	private String email;
	private String password;
	private String telefonnumber;
	private Member members;
	private Accountant accountant;
	private Helper helpers;
	private Lessee lessees;
	private Admin admins;
	private Donator donator;
	private Set<Task> taskses = new HashSet<Task>(0);

	public User() {
	}

	public User(String firstName, String lastName, Date birthdate, String email, String password,
			String telefonnumber) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthdate = birthdate;
		this.email = email;
		this.password = password;
		this.telefonnumber = telefonnumber;
	}

	public User(String firstName, String lastName, Date birthdate, String email, String password, String telefonnumber,
			Member members, Accountant accountant, Helper helpers, Lessee lessees, Admin admins, Donator donator,
			Set<Task> taskses) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthdate = birthdate;
		this.email = email;
		this.password = password;
		this.telefonnumber = telefonnumber;
		this.members = members;
		this.accountant = accountant;
		this.helpers = helpers;
		this.lessees = lessees;
		this.admins = admins;
		this.donator = donator;
		this.taskses = taskses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "User_ID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "firstName", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", nullable = false, length = 10)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "telefonnumber", nullable = false, length = 45)
	public String getTelefonnumber() {
		return this.telefonnumber;
	}

	public void setTelefonnumber(String telefonnumber) {
		this.telefonnumber = telefonnumber;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Member getMembers() {
		return this.members;
	}

	public void setMembers(Member members) {
		this.members = members;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Accountant getAccountants() {
		return this.accountant;
	}

	public void setAccountants(Accountant accountants) {
		this.accountant = accountants;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Helper getHelpers() {
		return this.helpers;
	}

	public void setHelpers(Helper helpers) {
		this.helpers = helpers;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Lessee getLessees() {
		return this.lessees;
	}

	public void setLessees(Lessee lessees) {
		this.lessees = lessees;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Admin getAdmins() {
		return this.admins;
	}

	public void setAdmins(Admin admins) {
		this.admins = admins;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Donator getDonator() {
		return this.donator;
	}

	public void setDonator(Donator donator) {
		this.donator = donator;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Task> getTaskses() {
		return this.taskses;
	}

	public void setTaskses(Set<Task> taskses) {
		this.taskses = taskses;
	}

}
